# Generated by Django 3.0.6 on 2020-05-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='name',
            new_name='title',
        ),
    ]
